modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/NikitaCartes/DimensionalTracker/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "https://github.com/NikitaCartes/DimensionalTracker"
authors = "NikitaCartes"
description = '''
Colour nicknames depending on the player's dimension.
'''
side = "SERVER"

[[mixins]]
config = "dimensional-tracker.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "SERVER"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${supported_minecraft_version}"
ordering = "NONE"
side = "SERVER"
